
# Message
std_msgs/Header header

float64 joint_swing
float64 joint_boom
float64 joint_arm
float64 joint_bucket
# Autobox에서 보내주는 swing encoder angle
float64 joint_track

float64 bkt_pos_x
float64 bkt_pos_y
float64 bkt_pos_z

float64 bkt_lat
float64 bkt_lon
float64 bkt_height

float64 base_pos_x
float64 base_pos_y
float64 base_pos_z

float64 base_lat
float64 base_lon
float64 base_height

float64 roll
float64 pitch
float64 yaw
float64 gnss_heading